Remove messages for non-ERROR can_connect service checks
DataDog/jmxfetch pull request #369
Opened 2021-08-16 19:36 UTC by yzhan289

This PR removes messages for status that is not an ERROR for the `*.can_connect` service check.

Datadog is removing messages for integration checks that give OK status to reduce the load on the backend. There's a small scenario where `*.can_connect` gives a WARNING status along with a message. This WARNING is later converted into an OK, as only OK or ERROR statuses are used for `*.can_connect`.

2021-08-16 21:10 UTC, ofek requested changes

2021-08-16 21:10 UTC, ofek commented on src/main/java/org/datadog/jmxfetch/App.java
> +        if (status != Status.STATUS_ERROR) {
```suggestion
        if (status == Status.STATUS_OK) {
```

2021-08-16 21:12 UTC, ofek commented on src/main/java/org/datadog/jmxfetch/App.java
> +        if (status != Status.STATUS_ERROR) {
then remove https://github.com/DataDog/jmxfetch/blob/f398b502c30f409401bfdb21e57339119dcc1ba1/src/main/java/org/datadog/jmxfetch/App.java#L1194

2021-08-20 20:52 UTC, ofek approved these changes

2021-08-24 07:45 UTC, remeh approved these changes
LGT

2021-08-24 20:47 UTC, merged