Caleb/misbehaving jmx server enable configfile support and restructure
DataDog/jmxfetch pull request #464
Opened 2023-08-03 20:27 UTC by cmetz100

2023-08-03 20:51 UTC, scottopell reviewed
First pass, some of these may be stale already.

I'd like to keep some way of changing the values over time. This is what the `MetricsDAO` was used for, it ran on a timer and incremented the values forever.
Do you have any ideas for how we can accomplish this?

2023-08-03 20:51 UTC, scottopell commented on tools/misbehaving-jmx-server/configs/benchmark_config.yaml
> +        tabular_count: 3
```suggestion
        tabular_attribute_count: 3
```

2023-08-03 20:51 UTC, scottopell commented on tools/misbehaving-jmx-server/configs/benchmark_config.yaml
> +        attribute_count: 2
```suggestion
        scalar_attribute_count: 2
```

2023-08-03 20:51 UTC, scottopell commented on tools/misbehaving-jmx-server/configs/benchmark_config.yaml
> +        composite_count: 4
```suggestion
        composite_values_per_tabular_attribute: 4
```

this one is wordy, but something along these lines

2023-08-03 20:51 UTC, scottopell commented on tools/misbehaving-jmx-server/src/main/java/org/datadog/misbehavingjmxserver/App.java
> +    public AppSpec getConfig () {
```suggestion
    public AppSpec readConfigFileOnDisk () {
```

2023-08-03 20:51 UTC, scottopell commented on tools/misbehaving-jmx-server/src/main/java/org/datadog/misbehavingjmxserver/App.java
> +    public void initConfig() throws IOException {
this function doesn't seem all that useful to me, can we get rid of it?

2023-08-03 20:51 UTC, scottopell commented on tools/misbehaving-jmx-server/src/main/java/org/datadog/misbehavingjmxserver/App.java
> +            System.out.println("could not find your config file at " + yamlPath);
switch to `log.warn` or `log.error`.

2023-08-03 20:51 UTC, scottopell commented on tools/misbehaving-jmx-server/src/main/java/org/datadog/misbehavingjmxserver/App.java
> +class AppSpec {
todo -- a better name here. Not sure what I want it to be, but `AppSpec` doesn't mean anything, especially when we already have `AppConfig`

2023-08-03 20:51 UTC, scottopell commented on tools/misbehaving-jmx-server/src/main/java/org/datadog/misbehavingjmxserver/App.java
> +        String result = "";
Convert this to a stringbuilder

2023-08-03 20:51 UTC, scottopell commented on tools/misbehaving-jmx-server/src/main/java/org/datadog/misbehavingjmxserver/App.java
> +    public int bean_count;
hopefully its not painful, but ideally we could specify the yaml in snake_case and the fields here in camelCase

2023-08-03 20:51 UTC, scottopell commented on tools/misbehaving-jmx-server/src/main/java/org/datadog/misbehavingjmxserver/App.java
> +            AppSpec test = yaml.load(yamlInputStream);
```suggestion
            AppSpec results = yaml.load(yamlInputStream);
```

2023-08-03 20:51 UTC, scottopell commented on tools/misbehaving-jmx-server/src/main/java/org/datadog/misbehavingjmxserver/App.java
> +        if (config.rmiHost.equals("localhost")){
lets revert this. If this is a fix that we want we should make it in a separate PR

2023-08-03 20:51 UTC, scottopell commented on tools/misbehaving-jmx-server/src/main/java/org/datadog/misbehavingjmxserver/App.java
> +            System.out.println("updated config_path from env: " + config_path);
remove

2023-08-03 20:51 UTC, scottopell commented on tools/misbehaving-jmx-server/src/main/java/org/datadog/misbehavingjmxserver/App.java
> +            return test;
If it was successfully read, lets print a `log.info` saying "Read in config values from file at path X"

2023-08-03 20:51 UTC, scottopell commented on tools/misbehaving-jmx-server/src/main/java/org/datadog/misbehavingjmxserver/BeanManager.java
> +                log.warn("Could not unregister bean");
```suggestion
                log.warn("Could not unregister bean: ", e);
```

2023-08-03 20:51 UTC, scottopell commented on tools/misbehaving-jmx-server/src/main/java/org/datadog/misbehavingjmxserver/BeanManager.java
> +                e.printStackTrace();
```suggestion
```
(I know you just preserved what was there, but lets improve it a bit)

2023-08-03 20:51 UTC, scottopell commented on tools/misbehaving-jmx-server/src/main/java/org/datadog/misbehavingjmxserver/DynamicMBeanMetrics.java
> +            //System.out.println("Key is " + name + " Val is " + String.valueOf(entry.getValue()));
```suggestion
```

2023-08-03 20:51 UTC, scottopell commented on tools/misbehaving-jmx-server/src/main/java/org/datadog/misbehavingjmxserver/DynamicMBeanMetrics.java
> +        throw new UnsupportedOperationException("Not supported in this example.");
```suggestion
        throw new UnsupportedOperationException("Not supported in misbehaving-jmx-server.");
```
or similar

2023-08-03 20:51 UTC, scottopell commented on tools/misbehaving-jmx-server/src/main/java/org/datadog/misbehavingjmxserver/DynamicMBeanMetrics.java
> +                System.out.println("Tabular" + String.valueOf(i) + " didnt work");
switch to `log.warn`

2023-08-03 20:51 UTC, scottopell commented on tools/misbehaving-jmx-server/src/main/java/org/datadog/misbehavingjmxserver/DynamicMBeanMetrics.java
> +        RandomIdentifier idGen = new RandomIdentifier();
```suggestion
```
doesn't appear to be used

2023-08-04 20:19 UTC, scottopell commented on tools/misbehaving-jmx-server/src/main/java/org/datadog/misbehavingjmxserver/App.java
> +        // Uncomment this to be able to access jmx server on MacOS
lets not make this change as part of this PR.
This is what I'd call a "drive-by" change. The overall intention of this PR is to enable more configurable beans to be exposed and allow it to be driven by a config file on disk.  
This change is not related to this PR's intention and this change would benefit from further description, hence why I recommend to remove it.

2023-08-04 20:19 UTC, scottopell commented on tools/misbehaving-jmx-server/src/main/java/org/datadog/misbehavingjmxserver/App.java
> +            log.warn("JmxDomainConfigurations is null");
```suggestion
```
Above log covers this just fine, don't see the value in this secondary PR

2023-08-04 20:19 UTC, scottopell commented on tools/misbehaving-jmx-server/src/main/java/org/datadog/misbehavingjmxserver/App.java
> +        BeanSpec testDomaiBeanSpec = new BeanSpec(1, 1, 0, 0);
```suggestion
        BeanSpec testDomainBeanSpec = new BeanSpec(1, 1, 0, 0);
```

2023-08-09 15:26 UTC, scottopell requested changes
This is really coming together, I like the latest version. A few small changes I'd like, but we're about ready to ship this.

2023-08-09 15:26 UTC, scottopell commented on tools/misbehaving-jmx-server/src/main/java/org/datadog/misbehavingjmxserver/App.java
> +    public String config_path = "configs/benchmark_config.yaml";
```suggestion
    public String config_path = "./misbehaving_jmx_config.yaml";
```

Lets default it to the current directory

2023-08-09 15:26 UTC, scottopell commented on tools/misbehaving-jmx-server/src/main/java/org/datadog/misbehavingjmxserver/DynamicMBeanMetrics.java
> +                log.warn("Tabular" + String.valueOf(i) + " didnt work");
```suggestion
                log.warn("Tabular" + String.valueOf(i) + " threw an exception: ", e);
```
and then no need for the below `printStackTrace`

2023-08-09 15:27 UTC, scottopell commented
Can you add a description of the new config options and an example YAML file to the misbehaving-jmx-server README?

2023-08-09 19:23 UTC, scottopell reviewed
One more small `import` cleanup, and needs some readme changes, but otherwise this looks good to ship to me!

2023-08-09 19:23 UTC, scottopell commented on tools/misbehaving-jmx-server/src/main/java/org/datadog/misbehavingjmxserver/DynamicMBeanMetrics.java
> +import javax.management.*;
You likely don't need this line since you import each specific package below

2023-08-09 21:03 UTC, buraizu approved these changes
LGTM, approving with just a few updates per the [documentation style guide](https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md)

2023-08-10 18:18 UTC, scottopell submitted a review, later dismissed

2023-08-11 15:15 UTC, scottopell approved these changes

2023-08-14 16:44 UTC, merged