Caleb/add jmxfetch telemetry in code
DataDog/jmxfetch pull request #467
Opened 2023-08-08 19:05 UTC by cmetz100

2023-08-09 18:20 UTC, scottopell requested changes
Probably the last set of changes I'll request.
To re-iterate what we discussed, lets make the config option that turns this on and off be generic -- "JMXFetch Telemetry". Since the `domain` monitored by the telemetry instance is not specific to `instance` telemetry, the config option to turn it on and off should not be either.

2023-08-09 18:20 UTC, scottopell commented on src/main/java/org/datadog/jmxfetch/App.java
> +            if (newInstances.size() >= 1) {
Lets fold this into the above `if` statement with a `&&` to save some indentation levels.

2023-08-09 18:20 UTC, scottopell commented on src/main/java/org/datadog/jmxfetch/App.java
> +                log.info("Adding jmxfetch instance telemetry check");
```suggestion
                log.info("Adding jmxfetch telemetry check");
```

2023-08-09 18:20 UTC, scottopell commented on src/main/java/org/datadog/jmxfetch/App.java
> +                final Instance instance = instantiate(getInstanceTelemetryInstanceConfig(),
```suggestion
                final Instance instance = instantiate(getTelemetryInstanceConfig(),
```

2023-08-09 18:20 UTC, scottopell commented on src/main/java/org/datadog/jmxfetch/App.java
> +                         getInstanceTelemetryInitConfig(), "jmxfetch_telemetry_check",
```suggestion
                         getTelemetryInitConfig(), "jmxfetch_telemetry_check",
```

2023-08-09 18:20 UTC, scottopell commented on src/main/java/org/datadog/jmxfetch/AppConfig.java
> +            names = {"--instance_telemetry", "-it"},
```suggestion
            names = {"--jmxfetch_telemetry", "-it"},
```
or maybe `internal_telemetry`? or maybe just `telemetry`?

In the agent we simply use `telemetry`, so maybe that works for us here.

2023-08-10 16:46 UTC, scottopell requested changes

2023-08-10 16:46 UTC, scottopell commented on src/main/java/org/datadog/jmxfetch/App.java
> +        tags.add("jmx:fetch");
For this PR, lets not put any tags, just keep it as an empty list. This tag isn't particularly useful, I think this originated from some testing code.

In a follow-up PR, I'd like you to work on adding a tag that reflects the current version of JMXFetch. So `tags.add("jmxfetch_version:0.47.10")`.

2023-08-10 16:46 UTC, scottopell commented
Please add a changelog entry and address the one last comment about tags and this is good to go!

2023-08-10 17:19 UTC, drichards-87 submitted a review, later dismissed

2023-08-10 18:08 UTC, scottopell submitted a review, later dismissed

2023-08-10 18:16 UTC, scottopell approved these changes

2023-08-11 14:09 UTC, drichards-87 approved these changes

2023-08-11 15:22 UTC, merged